Parameters: { Phase: { Type: String, Default: "1" } }
Resources:
  Subnets:
    Type: AWS::DAX::SubnetGroup
    Properties:
      Description: !Sub phase ${Phase}
      SubnetIds: [subnet-2e0a500f, subnet-ab11fde7]
