package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/arn"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	cfntypes "github.com/aws/aws-sdk-go-v2/service/cloudformation/types"
	"github.com/aws/aws-sdk-go-v2/service/iam"
	iamtypes "github.com/aws/aws-sdk-go-v2/service/iam/types"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

type awsClients struct {
	cfg     aws.Config
	cfn     *cloudformation.Client
	iam     *iam.Client
	account string
	part    string
}

func newClients(ctx context.Context) (*awsClients, error) {
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return nil, err
	}
	id, err := sts.NewFromConfig(cfg).GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
	if err != nil {
		return nil, err
	}
	a, err := arn.Parse(aws.ToString(id.Arn))
	if err != nil {
		return nil, err
	}
	return &awsClients{cfg: cfg, cfn: cloudformation.NewFromConfig(cfg), iam: iam.NewFromConfig(cfg),
		account: aws.ToString(id.Account), part: a.Partition}, nil
}

// deployedTemplates fetches the processed templates of the stacks that already exist,
// so resources being removed still get delete permissions.
func (c *awsClients) deployedTemplates(ctx context.Context, tpls []*Template) ([]*Template, error) {
	var out []*Template
	for _, t := range tpls {
		if t.StackName == "" {
			continue
		}
		res, err := c.cfn.GetTemplate(ctx, &cloudformation.GetTemplateInput{
			StackName: aws.String(t.StackName), TemplateStage: cfntypes.TemplateStageProcessed,
		})
		if err != nil {
			if strings.Contains(err.Error(), "does not exist") {
				continue
			}
			return nil, fmt.Errorf("get template %s: %w", t.StackName, err)
		}
		dt, err := ParseTemplate("deployed:"+t.StackName, []byte(aws.ToString(res.TemplateBody)))
		if err != nil {
			return nil, err
		}
		// ponytail: deployed nested stacks aren't fetched, so a type removed only from a
		// nested stack loses its delete permissions; follow the nested stack ARNs if that bites.
		out = append(out, dt)
	}
	return out, nil
}

func (c *awsClients) policyArn(name string) string {
	return fmt.Sprintf("arn:%s:iam::%s:policy/%s", c.part, c.account, name)
}

// policyNames returns name, name-2, name-3, … for n documents.
func policyNames(base string, n int) []string {
	out := []string{base}
	for i := 2; i <= n; i++ {
		out = append(out, fmt.Sprintf("%s-%d", base, i))
	}
	return out
}

// existingActions reads the Allow actions of base, base-2, … until one is missing.
// parts is how many of them exist (0 when base itself does not).
func (c *awsClients) existingActions(ctx context.Context, base string) (actions []string, parts int, err error) {
	for i := 1; ; i++ {
		name := policyNames(base, i)[i-1]
		p, err := c.iam.GetPolicy(ctx, &iam.GetPolicyInput{PolicyArn: aws.String(c.policyArn(name))})
		var nse *iamtypes.NoSuchEntityException
		if errors.As(err, &nse) {
			return actions, i - 1, nil
		}
		if err != nil {
			return nil, 0, err
		}
		v, err := c.iam.GetPolicyVersion(ctx, &iam.GetPolicyVersionInput{
			PolicyArn: p.Policy.Arn, VersionId: p.Policy.DefaultVersionId,
		})
		if err != nil {
			return nil, 0, err
		}
		doc, err := url.QueryUnescape(aws.ToString(v.PolicyVersion.Document))
		if err != nil {
			return nil, 0, err
		}
		as, err := AllowedActions([]byte(doc))
		if err != nil {
			return nil, 0, err
		}
		actions = append(actions, as...)
	}
}

// putPolicy creates the managed policy or adds a new default version, deleting the
// oldest non-default version when the 5-version limit is reached.
func (c *awsClients) putPolicy(ctx context.Context, name string, doc PolicyDocument) error {
	b, _ := json.Marshal(doc)
	policyArn := c.policyArn(name)
	_, err := c.iam.GetPolicy(ctx, &iam.GetPolicyInput{PolicyArn: aws.String(policyArn)})
	var nse *iamtypes.NoSuchEntityException
	if errors.As(err, &nse) {
		_, err = c.iam.CreatePolicy(ctx, &iam.CreatePolicyInput{
			PolicyName:     aws.String(name),
			Description:    aws.String("CloudFormation execution role policy generated by cfn-exec-policy"),
			PolicyDocument: aws.String(string(b)),
		})
		return err
	}
	if err != nil {
		return err
	}
	vs, err := c.iam.ListPolicyVersions(ctx, &iam.ListPolicyVersionsInput{PolicyArn: aws.String(policyArn)})
	if err != nil {
		return err
	}
	if len(vs.Versions) >= 5 {
		var old []iamtypes.PolicyVersion
		for _, v := range vs.Versions {
			if !v.IsDefaultVersion {
				old = append(old, v)
			}
		}
		sort.Slice(old, func(i, j int) bool { return old[i].CreateDate.Before(*old[j].CreateDate) })
		if _, err := c.iam.DeletePolicyVersion(ctx, &iam.DeletePolicyVersionInput{
			PolicyArn: aws.String(policyArn), VersionId: old[0].VersionId,
		}); err != nil {
			return err
		}
	}
	_, err = c.iam.CreatePolicyVersion(ctx, &iam.CreatePolicyVersionInput{
		PolicyArn: aws.String(policyArn), PolicyDocument: aws.String(string(b)), SetAsDefault: true,
	})
	return err
}
