# Attaches a policy to the pre-created role cfnxp-strict-unbounded.
Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles: [cfnxp-strict-unbounded]
      PolicyDocument:
        Statement: [{Effect: Allow, Action: logs:CreateLogGroup, Resource: "*"}]
