# Attaches a policy to the pre-created role cfnxp-strict-app-target.
Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles: [cfnxp-strict-app-target]
      PolicyDocument:
        Version: "2012-10-17"
        Statement: [{Effect: Allow, Action: logs:CreateLogGroup, Resource: "*"}]
